services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile.websocket
    image: openhands:websocket-latest
    container_name: openhands-websocket-app-${DATE:-}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.51-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of ~/.openhands for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
      # WebSocket specific configurations
      - DEBUG=true
      - CORS_ALLOWED_ORIGINS=*
      - INSTALL_DOCKER=0
      - RUNTIME=local
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=3000
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=3001
      - SERVE_FRONTEND=true
    ports:
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s